version: '3.0'
 
services:
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: itstepdev
      MYSQL_DATABASE: zno
      MYSQL_USER: dbuser
      MYSQL_PASSWORD: dbpassword
    volumes:
      - dbdata:/var/lib/mysql
      - ./_MySQL_Init_Script:/docker-entrypoint-initdb.d
    restart: always

  zno:
    depends_on:
      - db
    image: itstepdev/zno
    build:
      context: .
    ports:
      - "8080:80"

volumes:
    dbdata:
